// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibycvtowlvwmgyzoveef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlieWN2dG93bHZ3bWd5em92ZWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2NjczMjgsImV4cCI6MjA3NTI0MzMyOH0.FSYHphhlV-eZu3Z1-XUQiyZlkKiwjmMLSrtGD6Ail_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});